# CSV

In [1]:
import csv
def read_data(filename):
    with open(filename, 'r') as csvfile:
        datareader = csv.reader(csvfile, delimiter=',')
        traindata = []
        for row in datareader:
            traindata.append(row)
    return (traindata)
read_data('ecsv.txt')

[['dog', 'cat', 'lion'], ['ant', 'bee', 'black ant']]

# Pandas 

In [14]:
#pip install pandas 
import pandas as pd 
df_train=pd.read_csv(r'train.csv')
df_train

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_width   ram  sc_h  sc_w  talk_time  \
0       0.6        188        2  ...       756  2549     9     7         19   
1       0.7        136        3  ...      1988  2631    17     3          7   
2       0.9        145        5  ...      1716  2603    11     2          9   
3       0.8        131        6  ...      1786  2769    16     8         11   
4       0.6        141        2  ...      1212  1411     8     2         15   
...     ...        ...      ...  ...       ...   ...   ...   ...        ...   
1995    0.8        106        6  ...      1890   668    13     4         19   
1996    0.2        187        4  ...      1965  2032    11    10         16   
1997    0.7        108        8  ...      1632  3057     9     1          5   
1998    0.1        145        5  ...       670   869    18    10         19   
1999    0.9        168        6  ...       754  3919    19     4          2   

      three_g  touch_screen  wifi  price_range  null value  
0           0             0     1            1         NaN  
1           1             1     0            2         NaN  
2           1             1     0            2         NaN  
3           1             0     0            2         NaN  
4           1             1     0            1         NaN  
...       ...           ...   ...          ...         ...  
1995        1             1     0            0         NaN  
1996        1             1     1            2         NaN  
1997        1             1     0            3         NaN  
1998        1             1     1            0         NaN  
1999        1             1     1            3         NaN  

[2000 rows x 22 columns]

In [15]:
df_train.shape[1]

22

In [16]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [17]:
df_train.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range', 'null value'],
      dtype='object')

In [18]:
# check for the null values 
df_train.isna().any()

battery_power    False
blue             False
clock_speed      False
dual_sim         False
fc               False
four_g           False
int_memory       False
m_dep            False
mobile_wt        False
n_cores          False
pc               False
px_height        False
px_width         False
ram              False
sc_h             False
sc_w             False
talk_time        False
three_g          False
touch_screen     False
wifi             False
price_range      False
null value        True
dtype: bool

In [22]:
df_train['null value'] = df_train['null value'].fillna(0)

In [23]:
df_train.fillna(0)

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_width   ram  sc_h  sc_w  talk_time  \
0       0.6        188        2  ...       756  2549     9     7         19   
1       0.7        136        3  ...      1988  2631    17     3          7   
2       0.9        145        5  ...      1716  2603    11     2          9   
3       0.8        131        6  ...      1786  2769    16     8         11   
4       0.6        141        2  ...      1212  1411     8     2         15   
...     ...        ...      ...  ...       ...   ...   ...   ...        ...   
1995    0.8        106        6  ...      1890   668    13     4         19   
1996    0.2        187        4  ...      1965  2032    11    10         16   
1997    0.7        108        8  ...      1632  3057     9     1          5   
1998    0.1        145        5  ...       670   869    18    10         19   
1999    0.9        168        6  ...       754  3919    19     4          2   

      three_g  touch_screen  wifi  price_range  null value  
0           0             0     1            1         0.0  
1           1             1     0            2         0.0  
2           1             1     0            2         0.0  
3           1             0     0            2         0.0  
4           1             1     0            1         0.0  
...       ...           ...   ...          ...         ...  
1995        1             1     0            0         0.0  
1996        1             1     1            2         0.0  
1997        1             1     0            3         0.0  
1998        1             1     1            0         0.0  
1999        1             1     1            3         0.0  

[2000 rows x 22 columns]

In [24]:
df_train.isna().any()

battery_power    False
blue             False
clock_speed      False
dual_sim         False
fc               False
four_g           False
int_memory       False
m_dep            False
mobile_wt        False
n_cores          False
pc               False
px_height        False
px_width         False
ram              False
sc_h             False
sc_w             False
talk_time        False
three_g          False
touch_screen     False
wifi             False
price_range      False
null value       False
dtype: bool

In [25]:
del df_train['null value']

In [26]:
df_train

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [28]:
#pip install numpy
import numpy as np

In [29]:
array=np.array([1, 2, 3])
print("We have created first array :\n",array)

We have created first array :
 [1 2 3]


In [30]:
array=np.arange(8)
print("Original array : \n", array)

Original array : 
 [0 1 2 3 4 5 6 7]


In [31]:
array = np.arange(8).reshape(2, 4)
print("\narray reshaped with 2 rows and 4 columns : \n", array)


array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]


In [32]:
array = np.arange(8).reshape(4 ,2)
print("\narray reshaped with 2 rows and 4 columns : \n", array)


array reshaped with 2 rows and 4 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
