# Experiment 6

## Assuming a set of documents that need to be classified, use the Naive Bayes Classifier model to perform this task. Built - in Java classes/API can be used to write the program. Calculate the accuracy, precision, and recall for your data set.

In [1]:
import pandas as pd
import warnings 
warnings.filterwarnings('ignore')
msg=pd.read_csv('naivetext1.csv',names=['message','label']) #Tabular form dta
print('Total instances in the dataset:',msg.shape[0])

Total instances in the dataset: 18


In [2]:
msg

message label
0                     I love this sandwich   pos
1                 This is an amazing place   pos
2       I feel very good about these beers   pos
3                     This is my best work   pos
4                     What an awesome view   pos
5            I do not like this restaurant   neg
6                 I am tired of this stuff   neg
7                   I can't deal with this   neg
8                     He is my sworn enemy   neg
9                      My boss is horrible   neg
10                This is an awesome place   pos
11  I do not like the taste of this juice    neg
12                         I love to dance   pos
13       I am sick and tired of this place   neg
14                    What a great holiday   pos
15          That is a bad locality to stay   neg
16          We will have good fun tomorrow   pos
17        I went to my enemy's house today   neg

In [6]:
msg['labelnum']=msg.label.map({'pos':1,'neg':0})
X=msg.message
Y=msg.label

In [7]:
X

0                       I love this sandwich
1                   This is an amazing place
2         I feel very good about these beers
3                       This is my best work
4                       What an awesome view
5              I do not like this restaurant
6                   I am tired of this stuff
7                     I can't deal with this
8                       He is my sworn enemy
9                        My boss is horrible
10                  This is an awesome place
11    I do not like the taste of this juice 
12                           I love to dance
13         I am sick and tired of this place
14                      What a great holiday
15            That is a bad locality to stay
16            We will have good fun tomorrow
17          I went to my enemy's house today
Name: message, dtype: object

In [8]:
Y

0      pos
1      pos
2      pos
3      pos
4      pos
5      neg
6      neg
7      neg
8      neg
9      neg
10     pos
11     neg
12     pos
13     neg
14     pos
15     neg
16     pos
17     neg
Name: label, dtype: object

In [9]:
print('\nThe message and its label of first 5 instances are listed below')
X5, Y5 = X[0:5], msg.label[0:5]
for x, y in zip(X5,Y5):
  print(x,',',y)


The message and its label of first 5 instances are listed below
I love this sandwich ,  pos
This is an amazing place ,  pos
I feel very good about these beers ,  pos
This is my best work ,  pos
What an awesome view ,  pos


In [10]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,Y)
print('\nDataset is split into Training and Testing samples')
print('Total training instances :', xtrain.shape[0])
print('Total testing instances :', xtest.shape[0])


Dataset is split into Training and Testing samples
Total training instances : 13
Total testing instances : 5


In [13]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
xtrain_dtm = count_vect.fit_transform(xtrain) #Sparse matrix
xtest_dtm = count_vect.transform(xtest)
print('\nTotal features extracted using CountVectorizer:',xtrain_dtm.shape[1])


Total features extracted using CountVectorizer: 46


In [15]:
xtrain_dtm

<13x46 sparse matrix of type '<class 'numpy.int64'>'
	with 66 stored elements in Compressed Sparse Row format>

In [16]:
print('\nFeatures for first 5 training instances are listed below')
df=pd.DataFrame(xtrain_dtm.toarray(),columns=count_vect.get_feature_names())
print(df[0:5])


Features for first 5 training instances are listed below
   about  am  amazing  an  and  awesome  bad  beers  best  boss  ...  this  \
0      0   0        0   0    0        0    0      0     0     1  ...     0   
1      0   0        0   0    0        0    1      0     0     0  ...     0   
2      0   0        0   1    0        1    0      0     0     0  ...     1   
3      0   0        0   0    0        0    0      0     1     0  ...     1   
4      0   0        0   0    0        0    0      0     0     0  ...     1   

   tired  to  tomorrow  very  we  what  will  with  work  
0      0   0         0     0   0     0     0     0     0  
1      0   1         0     0   0     0     0     0     0  
2      0   0         0     0   0     0     0     0     0  
3      0   0         0     0   0     0     0     0     1  
4      0   0         0     0   0     0     0     0     0  

[5 rows x 46 columns]


In [17]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(xtrain_dtm,ytrain)
predicted = clf.predict(xtest_dtm)

In [18]:
print('\nClassstification results of testing samples are given below')
for doc, p in zip(xtest, predicted):
    pred = 'pos' if p==1 else 'neg'
    print('%s -> %s ' % (doc, pred))


Classstification results of testing samples are given below
I love to dance -> neg 
I do not like the taste of this juice  -> neg 
I went to my enemy's house today -> neg 
I love this sandwich -> neg 
What an awesome view -> neg 


In [19]:
from sklearn.metrics import accuracy_score,recall_score,precision_score,confusion_matrix
print('\nAccuracy metrics')
print('Accuracy of the classifer is',accuracy_score(ytest,predicted))
print('Recall:{0}\n Precison:{1}'.format(recall_score(ytest,predicted, pos_label='positive',average='micro'),precision_score(ytest,predicted,pos_label='positive',average='micro')))
print('Confusion matrix')
print(confusion_matrix(ytest,predicted)) 


Accuracy metrics
Accuracy of the classifer is 0.4
Recall:0.4
 Precison:0.4
Confusion matrix
[[1 0 0]
 [2 1 0]
 [1 0 0]]
